name: p256_example
description: Demonstrates how to use the p256 plugin.
publish_to: "none"

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  variance_flutter_secp256r1:
    path: ../

  convert: any
  crypto: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
